---

jobs:
- name: test-cc-test-app 
  public: true
  plan:
  - do:
    - aggregate:
      - get: cc-test-app-repo
        trigger: true 
			- get: cc-test-app-module-repo
        trigger: true
    - aggregate:
      - task: run-unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: cc-test-app-repo
          run:
            path: cc-test-app-repo/test_app.sh

resources:
- name: cc-test-app-repo
  type: git
  source:
    uri: https://github.com/ohlemacher/cc_test_app.git
    branch: master
    # <<: *ghe

- name: cc-test-module-repo
  type: git
  source:
    uri: git@github.com:ohlemacher/cc_test_module.git
    branch: master
    # <<: *ghe
